--INNER JOIN
SELECT ORDERS.OrderID,ORDERS.OrderDate,CUSTOMERS.ContactName,CUSTOMERS.Country FROM ORDERS INNER JOIN CUSTOMERS
ON CUSTOMERS.CustomerID=ORDERS.CustomerID

SELECT CONTACTNAME ,COUNT(ORDERID) AS MIQDOR FROM ORDERS INNER JOIN CUSTOMERS
ON ORDERS.CustomerID=Customers.CustomerID
GROUP BY ContactName HAVING COUNT(ORDERID)>=10

 
SELECT ORDERDATE,ORDERID,FirstName,LastName FROM ORDERS INNER JOIN Employees
ON ORDERS.EmployeeID=Employees.EmployeeID
INNER JOIN CUSTOMERS ON ORDERS.CustomerID=CUSTOMERS.CustomerID

SELECT COUNT(ORDERID),FirstName,LastName FROM ORDERS INNER JOIN Employees
ON ORDERS.EmployeeID=Employees.EmployeeID
GROUP BY FIRSTNAME,LastName



SELECT COUNT(ORDERID),LastName+' '+SUBSTRING(FirstName,1,1)+'.' FROM ORDERS INNER JOIN Employees
ON ORDERS.EmployeeID=Employees.EmployeeID
GROUP BY FIRSTNAME,LastName


--OUTER JOIN
     --LEFT JOIN
     --RIGHT JOIN

  SELECT * FROM [Order Details]
  SELECT * FROM PRODUCTS
  --NARKHI UMUMII ZAKAZI HAR YAK PRODUCT
  SELECT ORDERID,SUM(UNITPRICE*Quantity) AS PRICE FROM [Order Details]
  GROUP BY OrderID

  SELECT TOP (5)COUNT(ORDERID) as miqdori_ORDERID,MONTH(OrderDate) AS MOOOH,YEAR(OrderDate) AS SOL FROM Orders
  GROUP BY MONTH(OrderDate),YEAR(OrderDate)
  ORDER BY SOL DESC
  

  SELECT COUNT(ORDERID) as miqdori_ORDERID,MONTH(OrderDate) AS MOOOH,YEAR(OrderDate) AS SOL FROM Orders
  WHERE YEAR(OrderDate)='1998' 
  GROUP BY MONTH(OrderDate),YEAR(OrderDate)
  
  SELECT CustomerID,COUNT(OrderID) AS ORDERID_SUM FROM ORDERS
  WHERE (YEAR(OrderDate)='1998' AND MONTH(OrderDate) IN ('3','4','5'))
  GROUP BY CustomerID HAVING COUNT(OrderID)>=5
  ORDER BY ORDERID_SUM DESC