create View PRODUCTPRICE20
AS
SELECT ProductID,ProductName,UnitPrice FROM PRODUCTS WHERE UNITPRICE>20

SELECT UNITPRICE,PRODUCTNAME FROM PRODUCTPRICE20



CREATE PROC _PRODUCTPRICE
AS
SELECT ProductID,ProductName,UnitPrice FROM PRODUCTS
WHERE UNITPRICE>20

EXEC _PRODUCTPRICE



CREATE PROC _PRODUCTPRICEV
@A INT
AS
SELECT ProductID,ProductName,UnitPrice FROM PRODUCTS
WHERE UNITPRICE>@A

EXEC _PRODUCTPRICEV 50




CREATE PROC _INSERTPRODUCT1
@NAME NVARCHAR(50),
@PRICE MONEY
AS
INSERT PRODUCTS(ProductNAME,UnitPrice) VALUES(@NAME,@PRICE)

EXEC _INSERTPRODUCT1 'APPLE',15

SELECT* FROM PRODUCTS


CREATE PROC _UPDATEPRODUCT2
@ID INT,
@PRICE MONEY
AS
UPDATE PRODUCTS SET UNITPRICE=@PRICE WHERE ProductID=@ID

EXEC _UPDATEPRODUCT2 78,30
SELECT* FROM PRODUCTS


CREATE PROC _REMOVEPRODUCT
@ID INT
AS
DELETE PRODUCTS WHERE ProductID=@ID

EXEC _REMOVEPRODUCT 78
SELECT * FROM PRODUCTS


